In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[-1])
print(arr[-4:])

1
9
[6 7 8 9]


In [ ]:
print(arr[0] + arr[1])

3


In [ ]:
print(arr[7]/arr[1])

4.0


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(arr[0,1] + arr[1,1])

9


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr[1, 1, 2])

12


In [ ]:
arr = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
